language: cpp
dist: trusty
cache: apt

env:
  - QT=qt56
- QT=qt57

os:
  - linux
  
addons:
  apt:
    sources:
      # gcc/g++ repository
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - g++-4.9
      #cmake
      - cmake
      - cmake-data

before_install:
  # Alternative Qt repository
  # sudo add-apt-repository ppa:beineri/opt-qt57-trusty -y
  - if [[ "$QT" == "qt56" ]]; then sudo apt-add-repository -y ppa:beineri/opt-qt561-trusty; fi
  - if [[ "$QT" == "qt57" ]]; then sudo apt-add-repository -y ppa:beineri/opt-qt57-trusty; fi
  - sudo apt-get update -qy

install:
# Qt install
  #- sudo apt-get install -qy qt57base
  #- source /opt/qt57/bin/qt57-env.sh
  - if [[ "$QT" == "qt56" ]]; then sudo apt-get update -qq; sudo apt-get install -qq qt56base qt56tools qt56declarative; fi
  - if [[ "$QT" == "qt57" ]]; then sudo apt-get update -qq; sudo apt-get install -qq qt57base qt57tools qt57declarative; fi
# g++ install
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  # CPP Unit install
  - sudo apt-get install libcppunit-dev

after_success:
# Launch tests
  - cd Tests/
  #- cmake CMakeLists.txt
  #- make --file Makefile
  - ./tests

script:
  - cd src/
  - cmake CMakeLists.txt
  - make --file Makefile -j2
  
### Tests ###
  # Qt repository
  #- sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa # marche
  # g++ repository
  #- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y # marche
  # g++ update : 2 versions
  #- if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.9; fi
  #- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 50
#after_failure:
  #- sudo apt-get install -qy qt56declarative #marche
  #- sudo apt-get install -qy qt56tools  #marche, inutile ?
  #- sudo apt-get install -qy qt56default   ne marche pas
  #- sudo apt-get install -qy qt56base-dev  ne marche pas
  #- sudo apt-get install -qy qt5base-dev   ne marche pas
  #- sudo apt-get install -qy qttools5-dev-tools  ne marche pas
  #- sudo apt-get install -qy qt5base   ne marche pas
  #- sudo apt-get install -qy qt5tools  ne marche pas
  #- sudo apt-get install -qy qt5declarative-dev
  #- sudo apt-get install -qy qtdeclarative5-dev
  #- sudo apt-get install -qy qtdeclarative5
