language: cpp
sudo: required
dist: trusty
cache: apt

os:
  - linux
  
addons:
  apt:
    sources:
      # gcc/g++ repository
      - ubuntu-toolchain-r-test
      - ubuntu-sdk-team
      - trusty-media
      # Qt 5.9
      #- sourceline: 'ppa:beineri/opt-qt591-trusty'
      #- george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - g++-5
      - cmake
      - cmake-data
      - build-essential
      - qt5-default
      - qttools5-dev-tools
      - qtbase5-dev
      - libcppunit-dev
      #- qt59tools
      #- qt59base     
      
install:
  # g++ install
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
 
after_success:
# Launch tests
  - cd Tests/
  - ./tests

script:
  - cd src/
  - cmake CMakeLists.txt
  - make --file Makefile -j2
