.TH "CoordinatesTestFixture" 3 "Mon May 9 2016" "Urbanisme" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CoordinatesTestFixture \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <test_coordinates\&.h>\fP
.PP
Inherits TestFixture\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetUp\fP ()"
.br
.RI "\fIOpérations avant les tests\&. \fP"
.ti -1c
.RI "void \fBtearDown\fP ()"
.br
.RI "\fIOpérations après les tests\&. \fP"
.ti -1c
.RI "void \fBtest_calcManhattan\fP ()"
.br
.ti -1c
.RI "void \fBtest_calcEuclidean\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Tests sur les méthodes de la classe \fBCoordinates\fP 
.SH "Member Function Documentation"
.PP 
.SS "void CoordinatesTestFixture::test_calcEuclidean ()"

.PP
\fBTest\fP
.RS 4
le calcul de la distance Euclidienne entre deux coordonnées 
.RE
.PP

.SS "void CoordinatesTestFixture::test_calcManhattan ()"

.PP
\fBTest\fP
.RS 4
le calcul de la distance Manhattan entre deux coordonnées 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Urbanisme from the source code\&.
