.TH "CoordinatesTestFixture" 3 "Tue Apr 19 2016" "Urbanisme" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CoordinatesTestFixture \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits TestFixture\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetUp\fP ()"
.br
.ti -1c
.RI "void \fBtearDown\fP ()"
.br
.ti -1c
.RI "void \fBtest_calcManhattan\fP ()"
.br
.ti -1c
.RI "void \fBtest_calcEuclidean\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Urbanisme from the source code\&.
