.TH "FieldTestFixture" 3 "Wed Apr 20 2016" "Urbanisme" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldTestFixture \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fieldtestfixture\&.h>\fP
.PP
Inherits TestFixture\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetUp\fP ()"
.br
.RI "\fIOpérations avant les tests\&. \fP"
.ti -1c
.RI "void \fBtearDown\fP ()"
.br
.RI "\fIOpérations après les tests\&. \fP"
.ti -1c
.RI "void \fBtest_containsValids\fP ()"
.br
.ti -1c
.RI "void \fBtest_containsInvalids\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Tests sur la méthode contains de la classe \fBField\fP 
.PP
\fBTest\fP
.RS 4

.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Urbanisme from the source code\&.
