.TH "FieldTestFixture" 3 "Jeudi 12 Mai 2016" "Version 0.5" "Urbanisme" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldTestFixture \- Tests sur la classe \fBField\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fieldtestfixture\&.h>\fP
.PP
Est dérivée de TestFixture\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "void \fBsetUp\fP ()"
.br
.RI "\fIOpérations avant les tests\&. \fP"
.ti -1c
.RI "void \fBtearDown\fP ()"
.br
.RI "\fIOpérations après les tests\&. \fP"
.ti -1c
.RI "void \fBtest_containsValids\fP ()"
.br
.ti -1c
.RI "void \fBtest_containsInvalids\fP ()"
.br
.ti -1c
.RI "void \fBtest_servingValids\fP ()"
.br
.in -1c
.SH "Description détaillée"
.PP 
Tests sur la classe \fBField\fP\&. 


.PP
\fBTest\fP
.RS 4

.RE
.PP

.SH "Documentation des fonctions membres"
.PP 
.SS "void FieldTestFixture::test_containsInvalids ()"

.PP
\fBTest\fP
.RS 4
de la méthode contains() sur des coordonnées hors de la surface Contains doit retourner faux 
.RE
.PP

.SS "void FieldTestFixture::test_containsValids ()"

.PP
\fBTest\fP
.RS 4
de la méthode contains() sur des coordonnées dans la surface Contains doit retourner vrai 
.RE
.PP

.SS "void FieldTestFixture::test_servingValids ()"

.PP
\fBTest\fP
.RS 4
de la méthode getServingRoads() sur des coordonnées dans la surface 
.RE
.PP


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Urbanisme à partir du code source\&.
