.TH "LoadProgress" 3 "Jeudi 12 Mai 2016" "Version 0.5" "Urbanisme" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LoadProgress \- Classe abstraite, pour suivre l'évolution des chargements (en %)  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <loadprogress\&.h>\fP
.PP
Dérivée par \fBLoadWindow\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "virtual void \fBsetProgress\fP (int pourcentage)=0"
.br
.ti -1c
.RI "virtual void \fBcloseProgress\fP ()=0"
.br
.in -1c
.SH "Description détaillée"
.PP 
Classe abstraite, pour suivre l'évolution des chargements (en %) 


.PP
\fBAuteur:\fP
.RS 4
Florian 
.RE
.PP

.SH "Documentation des fonctions membres"
.PP 
.SS "virtual void LoadProgress::closeProgress ()\fC [pure virtual]\fP"
Doit fermer ou terminer la progression 
.PP
Implémenté dans \fBLoadWindow\fP\&.
.SS "virtual void LoadProgress::setProgress (int pourcentage)\fC [pure virtual]\fP"
Doit mettre à jour de la valeur de la progression 
.PP
Implémenté dans \fBLoadWindow\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Urbanisme à partir du code source\&.
