.TH "LocalSearch" 3 "Mon May 9 2016" "Version 0.1" "Urbanisme" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LocalSearch \- La classe chargée d'effectuer des recherches locales sur les différentes solutions TODO ajouter les entrées et sorties\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <localsearch\&.h>\fP
.SS "Public Member Functions"

.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "\fBLocalSearch\fP (\fBField\fP *_field, const \fBParameters\fP *_params)"
.br
.ti -1c
.RI "\fBLocalSearch\fP (const \fBLocalSearch\fP &other)"
.br
.in -1c
.in -1c
.in +1c
.ti -1c
.RI "void \fBinitSolution\fP ()"
.br
.ti -1c
.RI "bool \fBaddRoadUsable\fP ()"
.br
.ti -1c
.RI "bool \fBaddRoadsAccess\fP (unsigned nbToAdd)"
.br
.in -1c
.SH "Detailed Description"
.PP 
La classe chargée d'effectuer des recherches locales sur les différentes solutions TODO ajouter les entrées et sorties\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "LocalSearch::LocalSearch (\fBField\fP * _field, const \fBParameters\fP * _params)"
Constructeur d'une recherche locale à partir d'une surface existante et des paramètres des routes\&. La surface sera modifiée 
.PP
\fBParameters:\fP
.RS 4
\fI_field\fP Surface déjà instanciée 
.br
\fI_params\fP Paramètres des routes
.RE
.PP
.SS ""
.PP
Constructeurs 
.SS ""

.SS "LocalSearch::LocalSearch (const \fBLocalSearch\fP & other)"
Constructeur d'une recherche locale par recopie La surface de l'autre instance est recopiée 
.PP
\fBParameters:\fP
.RS 4
\fIother\fP Instance à recopier 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "bool LocalSearch::addRoadsAccess (unsigned nbToAdd)"
Tente l'ajout d'un chemin (série de routes) avec pour objectif d'améliorer l'accessibilité\&. 
.PP
\fBReturns:\fP
.RS 4
faux si aucune route n'a pu être ajoutée car il n'y a aucun placement de chemin permettant d'obtenir une solution réalisable avec une accessibilité meilleures ou équivalente\&. 
.RE
.PP

.SS "bool LocalSearch::addRoadUsable ()"
Tente l'ajout d'une route avec pour objectif d'augmenter le nombre de parcelles exploitables\&. 
.PP
\fBReturns:\fP
.RS 4
faux si aucune route n'a pu être ajoutée car il n'y a aucun placement de route permettant d'obtenir une solution réalisable avec un nombre de parcelles exploitables supérieur ou égal au nombre courant\&. 
.RE
.PP
TODO est-ce utile de soustraire le nombre de voisin, mettre un coef, \&.\&.\&. ? OUI, ça a une utilité, pour éviter de coller 2 routes 
.SS "void LocalSearch::initSolution ()"
Relie les entrées et sorties entre elles, de manière directe
.PP
.SS ""
.PP
Recherche locale 
.SS ""


.SH "Author"
.PP 
Generated automatically by Doxygen for Urbanisme from the source code\&.
