.TH "MinPathRoadTestFixture" 3 "Mon May 9 2016" "Urbanisme" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MinPathRoadTestFixture \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <minpathroadtestfixture\&.h>\fP
.PP
Inherits TestFixture\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetUp\fP ()"
.br
.RI "\fIOpérations avant les tests\&. \fP"
.ti -1c
.RI "void \fBtearDown\fP ()"
.br
.RI "\fIOpérations après les tests\&. \fP"
.ti -1c
.RI "void \fBtest_validsPath\fP ()"
.br
.ti -1c
.RI "void \fBtest_sameParcel\fP ()"
.br
.ti -1c
.RI "void \fBtest_invalidsPath\fP ()"
.br
.ti -1c
.RI "void \fBtest_findVisisted\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Tests sur la méthode calcRoadDistance() de la classe \fBEvaluation\fP 
.PP
\fBTest\fP
.RS 4

.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void MinPathRoadTestFixture::setUp ()"

.PP
Opérations avant les tests\&. Initialisation 
.SS "void MinPathRoadTestFixture::test_findVisisted ()"

.PP
\fBTest\fP
.RS 4
d'un find() sur un vecteur de coordonnée, utilisé dans recCalcRoadDistance, lors de l'ajout d'un voisin d'une route 
.RE
.PP

.SS "void MinPathRoadTestFixture::test_invalidsPath ()"

.PP
\fBTest\fP
.RS 4
de la méthode calcRoadDistance() entre des parcelles non 'reliées' par des routes La méthode doit alors retourner l'infini 
.RE
.PP

.SS "void MinPathRoadTestFixture::test_sameParcel ()"

.PP
\fBTest\fP
.RS 4
de la méthode calcRoadDistance() entre une parcelle et elle-même La méthode doit alors retourner 0 
.RE
.PP

.SS "void MinPathRoadTestFixture::test_validsPath ()"

.PP
\fBTest\fP
.RS 4
de la méthode calcRoadDistance() entre des parcelles 'reliées' par des routes La méthode doit alors retourner une valeur supérieure à 0 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Urbanisme from the source code\&.
