.TH "MyClassTestFixture" 3 "Wed Apr 20 2016" "Urbanisme" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MyClassTestFixture \- Classe 'coquille' : ne pas utiliser Tests sur les méthodes de la classe Dummy\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <test_my_class_dummy\&.h>\fP
.PP
Inherits TestFixture\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetUp\fP ()"
.br
.ti -1c
.RI "void \fBtearDown\fP ()"
.br
.ti -1c
.RI "void \fBtest_set\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Classe 'coquille' : ne pas utiliser Tests sur les méthodes de la classe Dummy\&. 


.PP
\fBTest\fP
.RS 4

.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Urbanisme from the source code\&.
