.TH "Parameters" 3 "Wed Apr 20 2016" "Urbanisme" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Parameters \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParameters\fP (unsigned _road_width, unsigned _serve_distance)"
.br
.ti -1c
.RI "unsigned \fBget_road_width\fP () const "
.br
.ti -1c
.RI "unsigned \fBget_serve_distance\fP () const "
.br
.ti -1c
.RI "void \fBset_road_width\fP (unsigned width)"
.br
.ti -1c
.RI "void \fBset_serve_distance\fP (unsigned distance)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Urbanisme from the source code\&.
