.TH "Resolution" 3 "Mon May 9 2016" "Version 0.1" "Urbanisme" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Resolution \- La classe effectuant l'ensemble de la résolution et le front Pareto Elle contient l'intégralité des données du problème et est chargée de lancer les algos, de stocker les solutions et de construire le front pareto résultant\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <resolution\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBResolution\fP (unsigned nbCols, unsigned nbRows, unsigned serveDistance, unsigned roadsWidth)"
.br
.ti -1c
.RI "\fBResolution\fP (unsigned nbCols, unsigned nbRows, unsigned serveDistance, unsigned roadsWidth, std::list< \fBCoordinates\fP > &ins_outs)"
.br
.ti -1c
.RI "\fBResolution\fP (const \fBField\fP &field, const \fBParameters\fP &_params)"
.br
.ti -1c
.RI "void \fBevaluateBothObjectives\fP (\fBEvaluation\fP &myEvaluation)"
.br
.in -1c
.SH "Detailed Description"
.PP 
La classe effectuant l'ensemble de la résolution et le front Pareto Elle contient l'intégralité des données du problème et est chargée de lancer les algos, de stocker les solutions et de construire le front pareto résultant\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Resolution::Resolution (unsigned nbCols, unsigned nbRows, unsigned serveDistance, unsigned roadsWidth)"
Constructeur d'une résolution à partir de tous les paramètres du problème 
.PP
\fBParameters:\fP
.RS 4
\fInbCols\fP Largeur de la surface 
.br
\fInbRows\fP Hauteur de la surface 
.br
\fIserveDistance\fP Distance de desserte des parcelles par les routes 
.br
\fIroadsWidth\fP Largeur des routes 
.RE
.PP

.SS "Resolution::Resolution (unsigned nbCols, unsigned nbRows, unsigned serveDistance, unsigned roadsWidth, std::list< \fBCoordinates\fP > & ins_outs)"
Constructeur d'une résolution à partir de tous les paramètres du problème, avec une liste d'entrées et sorties 
.PP
\fBParameters:\fP
.RS 4
\fInbCols\fP Largeur de la surface 
.br
\fInbRows\fP Hauteur de la surface 
.br
\fIserveDistance\fP Distance de desserte des parcelles par les routes 
.br
\fIroadsWidth\fP Largeur des routes 
.br
\fIins_outs\fP Liste d'entrées/sorties de la surface 
.RE
.PP

.SS "Resolution::Resolution (const \fBField\fP & field, const \fBParameters\fP & _params)"
Construit l'instance en recopiant une surface et des paramètres existants 
.PP
\fBParameters:\fP
.RS 4
\fIfield\fP 
.br
\fI_params\fP 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void Resolution::evaluateBothObjectives (\fBEvaluation\fP & myEvaluation)"
Evalue les deux objectifs TODO mettre à jour le front pareto 
.PP
\fBParameters:\fP
.RS 4
\fImyEvaluation\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Urbanisme from the source code\&.
