.TH "Resolution" 3 "Jeudi 12 Mai 2016" "Version 0.5" "Urbanisme" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Resolution \- La classe effectuant l'ensemble de la résolution et le front Pareto Elle contient l'intégralité des données du problème et est chargée de lancer les algos, de stocker les solutions et de construire le front pareto résultant\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <resolution\&.h>\fP
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "void \fBlocalSearchAccessObjective\fP (const \fBLocalSearch\fP &localSearch)"
.br
.in -1c
.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "\fBResolution\fP (unsigned nbCols, unsigned nbRows, unsigned serveDistance, unsigned roadsWidth)"
.br
.ti -1c
.RI "\fBResolution\fP (unsigned nbCols, unsigned nbRows, unsigned serveDistance, unsigned roadsWidth, std::list< \fBCoordinates\fP > &ins_outs)"
.br
.ti -1c
.RI "\fBResolution\fP (const \fBField\fP &field, const \fBParameters\fP &_params)"
.br
.in -1c
.in -1c
.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "void \fBevaluateBothObjectives\fP (\fBEvaluation\fP &myEvaluation)"
.br
.ti -1c
.RI "int \fBspread\fP (const \fBEvaluation\fP *eval)"
.br
.in -1c
.in -1c
.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "void \fBlocalSearchUsableObjective\fP (const \fBLocalSearch\fP &localSearch)"
.br
.in -1c
.in -1c
.SH "Description détaillée"
.PP 
La classe effectuant l'ensemble de la résolution et le front Pareto Elle contient l'intégralité des données du problème et est chargée de lancer les algos, de stocker les solutions et de construire le front pareto résultant\&. 
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "Resolution::Resolution (unsigned nbCols, unsigned nbRows, unsigned serveDistance, unsigned roadsWidth)"
Constructeur d'une résolution à partir de tous les paramètres du problème 
.PP
\fBParamètres:\fP
.RS 4
\fInbCols\fP Largeur de la surface 
.br
\fInbRows\fP Hauteur de la surface 
.br
\fIserveDistance\fP Distance de desserte des parcelles par les routes 
.br
\fIroadsWidth\fP Largeur des routes
.RE
.PP
.SS ""
.PP
Constructeurs 
.SS ""

.SS "Resolution::Resolution (unsigned nbCols, unsigned nbRows, unsigned serveDistance, unsigned roadsWidth, std::list< \fBCoordinates\fP > & ins_outs)"
Constructeur d'une résolution à partir de tous les paramètres du problème, avec une liste d'entrées et sorties 
.PP
\fBParamètres:\fP
.RS 4
\fInbCols\fP Largeur de la surface 
.br
\fInbRows\fP Hauteur de la surface 
.br
\fIserveDistance\fP Distance de desserte des parcelles par les routes 
.br
\fIroadsWidth\fP Largeur des routes 
.br
\fIins_outs\fP Liste d'entrées/sorties de la surface 
.RE
.PP

.SS "Resolution::Resolution (const \fBField\fP & field, const \fBParameters\fP & _params)"
Construit l'instance en recopiant une surface et des paramètres existants 
.PP
\fBParamètres:\fP
.RS 4
\fIfield\fP 
.br
\fI_params\fP 
.RE
.PP

.SH "Documentation des fonctions membres"
.PP 
.SS "void Resolution::evaluateBothObjectives (\fBEvaluation\fP & myEvaluation)"
Evalue les deux objectifs TODO mettre à jour le front pareto 
.PP
\fBParamètres:\fP
.RS 4
\fImyEvaluation\fP 
.SS ""
.RE
.PP
\fBEvaluation\fP et Pareto 
.SS ""

.SS "void Resolution::localSearchAccessObjective (const \fBLocalSearch\fP & localSearch)"
Exécute la recherche locale permettant de maximiser l'accessibilité 
.PP
\fBParamètres:\fP
.RS 4
\fIlocalSearch\fP Recherche locale effectuant les opérations 
.RE
.PP
\fBVoir également:\fP
.RS 4
Utiliser un signal pour mettre à jour l'affichage pendant les recherche ? 
.RE
.PP

.SS "void Resolution::localSearchUsableObjective (const \fBLocalSearch\fP & localSearch)"
Exécute la recherche locale permettant de maximiser le nombre de parcelles exploitables 
.PP
\fBParamètres:\fP
.RS 4
\fIlocalSearch\fP Recherche locale effectuant les opérations 
.RE
.PP
\fBVoir également:\fP
.RS 4
Utiliser un signal pour mettre à jour l'affichage pendant les recherche ?
.RE
.PP
.SS ""
.PP
Recherches locales 
.SS ""

.SS "int Resolution::spread (const \fBEvaluation\fP * eval)"
Effectue une propagation à partir de la solution courante : toutes les solutions précédentes dominées par la solution sont supprimées 
.PP
\fBParamètres:\fP
.RS 4
\fIeval\fP \fBEvaluation\fP courante 
.RE
.PP
\fBRenvoie:\fP
.RS 4
le nombre de solutions supprimées 
.RE
.PP


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Urbanisme à partir du code source\&.
