.TH "test" 3 "Jeudi 12 Mai 2016" "Version 0.5" "Urbanisme" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test \- Liste des tests 

.IP "\fBMembre \fBCoordinatesTestFixture::test_calcEuclidean\fP ()\fP" 1c
le calcul de la distance Euclidienne entre deux coordonnées  
.IP "\fBMembre \fBCoordinatesTestFixture::test_calcManhattan\fP ()\fP" 1c
le calcul de la distance Manhattan entre deux coordonnées  
.IP "\fBMembre \fBField::createExample\fP ()\fP" 1c
Utile seulement pour les tests  
.IP "\fBClasse \fBFieldTestFixture\fP \fP" 1c
.IP "\fBMembre \fBFieldTestFixture::test_containsInvalids\fP ()\fP" 1c
de la méthode contains() sur des coordonnées hors de la surface Contains doit retourner faux  
.IP "\fBMembre \fBFieldTestFixture::test_containsValids\fP ()\fP" 1c
de la méthode contains() sur des coordonnées dans la surface Contains doit retourner vrai  
.IP "\fBMembre \fBFieldTestFixture::test_servingValids\fP ()\fP" 1c
de la méthode getServingRoads() sur des coordonnées dans la surface  
.IP "\fBClasse \fBMinPathRoadTestFixture\fP \fP" 1c
.IP "\fBMembre \fBMinPathRoadTestFixture::test_findVisisted\fP ()\fP" 1c
d'un find() sur un vecteur de coordonnée, utilisé dans recCalcRoadDistance, lors de l'ajout d'un voisin d'une route  
.IP "\fBMembre \fBMinPathRoadTestFixture::test_invalidsPath\fP ()\fP" 1c
de la méthode calcRoadDistance() entre des parcelles non 'reliées' par des routes La méthode doit alors retourner l'infini  
.IP "\fBMembre \fBMinPathRoadTestFixture::test_sameParcel\fP ()\fP" 1c
de la méthode calcRoadDistance() entre une parcelle et elle-même La méthode doit alors retourner 0  
.IP "\fBMembre \fBMinPathRoadTestFixture::test_validsPath\fP ()\fP" 1c
de la méthode calcRoadDistance() entre des parcelles 'reliées' par des routes La méthode doit alors retourner une valeur supérieure à 0  
.IP "\fBClasse \fBNextCoordinatesTestFixture\fP \fP" 1c
.IP "\fBMembre \fBNextCoordinatesTestFixture::test_invalidsCoords\fP ()\fP" 1c
de la méthode nextCoordinates() sur des coordonnées non 'valides' Doit retourner faux et ne pas modifier la coordonnée en entrée  
.IP "\fBMembre \fBNextCoordinatesTestFixture::test_validsCoords\fP ()\fP" 1c
de la méthode nextCoordinates() sur des coordonnées 'valides' Doit retourner vrai et modifier la coordonnée en entrée 
.PP

